#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'p:teal'
    template = '{{ .UserName }}'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:text'
    template = ' in '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:blue'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:mauve'
    background = 'transparent'
    template = "{{ .HEAD }}{{ if (.Working.Changed) }}*{{ end }}{{ if (.Staging.Changed) }}+{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}"

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

    # [blocks.segments.properties]
    #   branch_icon = ' '
    #   cherry_pick_icon = ' '
    #   commit_icon = ' '
    #   fetch_status = false
    #   fetch_upstream_icon = false
    #   merge_icon = ' '
    #   no_commits_icon = ' '
    #   rebase_icon = ' '
    #   revert_icon = ' '
    #   tag_icon = ' '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'p:pink'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:lavender{{end}}",
    ]
    template = ''

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:lavender{{end}}",
  ]
  background = 'transparent'
  template = '{{now | date "15:04:05"}} ❯ '

[secondary_prompt]
  foreground = 'p:lavender'
  background = 'transparent'
  template = '❯❯ '

[palette]
  pink = '#F5C2E7'
  mauve = '#CBA6F7'
  red = '#F38BA8'
  yellow = '#F9E2AF'
  teal = '#94E2D5'
  blue = '#89B4FA'
  lavender = '#B4BEFE'
  text = '#CDD6F4'

